---

- hosts: all
  tasks:
    - name: Push cloudformation stack
      cloudformation:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        stack_name: "hello-app"
        state: present
        region: eu-west-1
        template: cloudformation.json
        template_parameters:
          KeyName: "{{ aws_key_name }}"
          InstanceImageId: "{{ aws_ami_id }}"
        tags:
          Stack: "hello-app"
          Ami: "{{ aws_ami_id }}"

		 
		
    ---
- hosts: droplets
  tasks:
    - name: Installs nginx web server
      apt: pkg=nginx state=installed update_cache=true
      notify:
        - start nginx

    - name: Upload default index.html for host
      copy: src=static_files/index.html dest=/usr/share/nginx/www/ mode=0644

  handlers:
    - name: start nginx
      service: name=nginx state=started

